name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8 
  # - pandas=2.0.3
  - pip=23.3.1
  - scikit-learn=0.24.1
  - matplotlib=3.2.2
  - plotly=4.4.1
  - pillow=8.1.2
  - numpy==1.23.4
  - mlflow=1.14.1
  - pip:
      - wandb==0.16.0
      - omegaconf==2.0.6